services:
  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - server
    environment:
      - SERVER_URL=http://server:3000

  server:
    build:
      context: .
      dockerfile: node_server/Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./node_server/.env